swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    username: romain.petrow@sio-loudun.fr
    password: Boulet86!
    host: smtp.ionos.fr 
    port: 587
    encryption: tls
    auth-mode: login
    stream_options:
        ssl:
          allow_self_signed: true
          verify_peer: false
          verify_peer_name: false
          
           